#########################################
# Sukka's Ruleset - Apple Domains
# Last Updated: 2026-08-05T12:33:04.405Z
# Size: 26
# License: AGPL 3.0
# Homepage: https://ruleset.skk.moe
# GitHub: https://github.com/SukkaW/Surge
#
# This file contains domains of Apple, Inc.
#
# $content-hash-v1$:D1NZxJ0P8otGR-pmWun3-MR6MHrTyyNdXdnytT_bmcg$
#########################################
DOMAIN,7h15.ru1353t.1s.m4d3.by.5ukk4w.skk.moe
DOMAIN-SUFFIX,me.com
DOMAIN-SUFFIX,apple.co
DOMAIN-SUFFIX,apple.com
DOMAIN-SUFFIX,appsto.re
DOMAIN-SUFFIX,apple.news
DOMAIN-SUFFIX,icloud.com
DOMAIN-SUFFIX,itunes.com
DOMAIN-SUFFIX,aaplimg.com
DOMAIN-SUFFIX,appstore.com
DOMAIN-SUFFIX,apple-dns.net
DOMAIN-SUFFIX,cdn-apple.com
DOMAIN-SUFFIX,apple-mapkit.com
DOMAIN-SUFFIX,apple-cloudkit.com
DOMAIN-SUFFIX,icloud-content.com
DOMAIN-SUFFIX,organicfruitapps.com
DOMAIN-SUFFIX,push-apple.com.akadns.net
PROCESS-NAME,com.apple.geod
PROCESS-NAME,mapspushd
PROCESS-NAME,com.apple.Maps
PROCESS-NAME,apsd
PROCESS-NAME,fmfd
PROCESS-NAME,findmydevice-user-agent
PROCESS-NAME,CoreLocationAgent
PROCESS-NAME,WeatherWidget
IP-CIDR,17.0.0.0/8,no-resolve
################## EOF ##################
