#########################################
# Sukka's Ruleset - Domestic CDN Domains
# Last Updated: 2026-09-26T17:58:29.393Z
# Size: 18
# License: AGPL 3.0
# Homepage: https://ruleset.skk.moe
# GitHub: https://github.com/SukkaW/Surge
#
# This file contains CDN domains of domestic services that have somewhat optimal performance both in China and abroad.
# All entries are included in the domestic ruleset as well.
#
# $content-hash-v1$:GzHSG7BCh-dSD8Y2NV379lHxJ1rTp4AlB4Ulvi7zMro$
#########################################
DOMAIN,7h15.ru1353t.1s.m4d3.by.5ukk4w.skk.moe
DOMAIN-SUFFIX,tbcdn.cn
DOMAIN-SUFFIX,hdslb.com
DOMAIN-SUFFIX,qhimg.com
DOMAIN-SUFFIX,qhres.com
DOMAIN-SUFFIX,zhimg.com
DOMAIN-SUFFIX,alicdn.com
DOMAIN-SUFFIX,qhimgs.com
DOMAIN-SUFFIX,qhres2.com
DOMAIN-SUFFIX,sinaimg.cn
DOMAIN-SUFFIX,biliimg.com
DOMAIN-SUFFIX,sinaimg.com
DOMAIN-SUFFIX,360buyimg.com
DOMAIN-SUFFIX,music.126.net
DOMAIN-SUFFIX,alipayobjects.com
DOMAIN,registry.npmmirror.com
DOMAIN-SUFFIX,tx-safety-video.acfun.cn
DOMAIN-SUFFIX,ali-safety-video.acfun.cn
################## EOF ##################
