#########################################
# Sukka's Ruleset - Large Files Hosting IPs
# Last Updated: 2026-07-31T17:36:02.314Z
# Size: 1
# License: AGPL 3.0
# Homepage: https://ruleset.skk.moe
# GitHub: https://github.com/SukkaW/Surge
#
# This file contains ruleset for software updating & large file hosting.
#
# $content-hash-v1$:R841hmQM1WX26sFJPfRlUiDT-zRumkoeTrPttOiI7sE$
#########################################
DOMAIN,7h15_ru1353t_1s_m4d3_by_5ukk4w.skk.moe
################## EOF ##################