#########################################
# Sukka's Ruleset - Direct
# Last Updated: 2026-07-31T16:18:56.693Z
# Size: 3
# License: AGPL 3.0
# Homepage: https://ruleset.skk.moe
# GitHub: https://github.com/SukkaW/Surge
#########################################
DOMAIN,7h15_ru1353t_1s_m4d3_by_5ukk4w.skk.moe
DOMAIN-SUFFIX,engage.cloudflareclient.com
PROCESS-NAME,nmap
################## EOF ##################