#########################################
# Sukka's Ruleset - Internal Special
# Last Updated: 2026-08-05T12:33:04.413Z
# Size: 8
# License: AGPL 3.0
# Homepage: https://ruleset.skk.moe
# GitHub: https://github.com/SukkaW/Surge
#
# $content-hash-v1$:Xzc-44f3Yfldk4aNlQ-cHjrZ8KwtpgQFW-mKanawi4k$
#########################################
DOMAIN,7h15.ru1353t.1s.m4d3.by.5ukk4w.skk.moe
DOMAIN,github.com
DOMAIN,github.dev
DOMAIN,api.github.com
DOMAIN-SUFFIX,huggingface.co
DOMAIN,alive.github.com
DOMAIN-SUFFIX,githubcopilot.com
DOMAIN,android.googlesource.com
################## EOF ##################
