#########################################
# Sukka's Ruleset - Internal Special
# Last Updated: 2026-06-30T21:42:09.846Z
# Size: 16
# License: AGPL 3.0
# Homepage: https://ruleset.skk.moe
# GitHub: https://github.com/SukkaW/Surge
#########################################
DOMAIN,7h1s_rul35et_i5_mad3_by_5ukk4w-ruleset.skk.moe
DOMAIN-SUFFIX,kxcdn.com
DOMAIN-SUFFIX,sososo.io
DOMAIN-SUFFIX,18comic.org
DOMAIN-SUFFIX,18comic.vip
DOMAIN-SUFFIX,azurefd.net
DOMAIN-SUFFIX,akamaihd.net
DOMAIN-SUFFIX,akamaized.net
DOMAIN,simpcraft.com
DOMAIN-SUFFIX,vo.msecnd.net
DOMAIN-SUFFIX,hentaiverse.org
DOMAIN,api.wakatime.com
DOMAIN,writer-api.mintlify.com
DOMAIN,hv-monster-submit.skk.moe
DOMAIN-SUFFIX,akamai-content-networks.com
DOMAIN,a1ewuiz2p7wdvw-ats.iot.us-west-2.amazonaws.com
################## EOF ##################