#########################################
# Sukka's Ruleset - Apple Intelligence
# Last Updated: 2026-07-31T17:36:02.309Z
# Size: 6
# License: AGPL 3.0
# Homepage: https://ruleset.skk.moe
# GitHub: https://github.com/SukkaW/Surge
#
# This file contains domains of OpenAI, Claude.
#
# $content-hash-v1$:8cjvaS6V7EeOAnv44M0R3-e8NSiL_Gc40R01BP3u6DM$
#########################################
DOMAIN,7h15_ru1353t_1s_m4d3_by_5ukk4w.skk.moe
DOMAIN,cp4.cloudflare.com
DOMAIN,apple-relay.apple.com
DOMAIN,gspe1-ssl.ls.apple.com
DOMAIN,apple-relay.cloudflare.com
DOMAIN,apple-relay.fastly-edge.com
################## EOF ##################