#########################################
# Sukka's Ruleset - Domestic CDN Domains
# Last Updated: 2026-09-22T18:38:06.779Z
# Size: 3
# License: AGPL 3.0
# Homepage: https://ruleset.skk.moe
# GitHub: https://github.com/SukkaW/Surge
#
# This file contains CDN domains of domestic services that should use DIRECT both in China and abroad.
# Place this ruleset before domestic when routing other domestic traffic back to China.
# All entries are also included in the domestic ruleset.
#
# $content-hash-v1$:rqFtqwmMPQiE-_lA5FfB0GUPgkHMVsiPHXJowlgELLo$
#########################################
DOMAIN,7h15.ru1353t.1s.m4d3.by.5ukk4w.skk.moe
DOMAIN-SUFFIX,hdslb.com
DOMAIN-SUFFIX,music.126.net
################## EOF ##################
