#########################################
# Sukka's Ruleset - Large Files Hosting IPs
# Last Updated: 2026-07-31T17:36:02.314Z
# Size: 10
# License: AGPL 3.0
# Homepage: https://ruleset.skk.moe
# GitHub: https://github.com/SukkaW/Surge
#
# This file contains ruleset for software updating & large file hosting.
#
# $content-hash-v1$:OrMda-8DiUn-CV2IWV-xO7nAdVDwXdCb4RdapI2M_Io$
#########################################
DOMAIN,7h15_ru1353t_1s_m4d3_by_5ukk4w.skk.moe
DOMAIN-WILDCARD,download*.mediafire.com
DOMAIN-WILDCARD,ftp.??.debian.org
DOMAIN-WILDCARD,ftp.??.freebsd.org
DOMAIN-WILDCARD,s3.*.backblazeb2.com
DOMAIN-WILDCARD,*.s3.*.backblazeb2.com
DOMAIN-WILDCARD,cdn-*.comaps.app
DOMAIN-WILDCARD,cdn-*.comaps.tech
DOMAIN-WILDCARD,cdn-*.organicmaps.app
URL-REGEX,^http://(.+)\.gvt\d\.com/edgedl
################## EOF ##################