#########################################
# Sukka's Ruleset - LAN
# Last Updated: 2026-06-30T21:42:09.921Z
# Size: 50
# License: AGPL 3.0
# Homepage: https://ruleset.skk.moe
# GitHub: https://github.com/SukkaW/Surge
#
# This file includes rules for LAN DOMAIN and reserved TLDs.
#########################################
DOMAIN,7h1s_rul35et_i5_mad3_by_5ukk4w-ruleset.skk.moe
DOMAIN-SUFFIX,lan
DOMAIN-SUFFIX,home
DOMAIN-SUFFIX,local
DOMAIN,unifi
DOMAIN-SUFFIX,router
DOMAIN,pi.hole
DOMAIN,aterm.me
DOMAIN-SUFFIX,internal
DOMAIN-SUFFIX,home.arpa
DOMAIN,ntt.setup
DOMAIN-SUFFIX,ui.direct
DOMAIN-SUFFIX,tplogin.cn
DOMAIN-SUFFIX,localdomain
DOMAIN-SUFFIX,plex.direct
DOMAIN-SUFFIX,tplinkap.net
DOMAIN-SUFFIX,asusrouter.com
DOMAIN,homerouter.cpe
DOMAIN,mobile.hotspot
DOMAIN-SUFFIX,tplinkwifi.net
DOMAIN-SUFFIX,10.in-addr.arpa
DOMAIN,router.asus.com
DOMAIN-SUFFIX,routerlogin.com
DOMAIN-SUFFIX,routerlogin.net
DOMAIN-SUFFIX,tplinkmodem.net
DOMAIN,repeater.asus.com
DOMAIN-SUFFIX,tplinkplclogin.net
DOMAIN-SUFFIX,tplinkrepeater.net
DOMAIN-SUFFIX,16.172.in-addr.arpa
DOMAIN-SUFFIX,17.172.in-addr.arpa
DOMAIN-SUFFIX,18.172.in-addr.arpa
DOMAIN-SUFFIX,19.172.in-addr.arpa
DOMAIN-SUFFIX,20.172.in-addr.arpa
DOMAIN-SUFFIX,21.172.in-addr.arpa
DOMAIN-SUFFIX,22.172.in-addr.arpa
DOMAIN-SUFFIX,23.172.in-addr.arpa
DOMAIN-SUFFIX,24.172.in-addr.arpa
DOMAIN-SUFFIX,25.172.in-addr.arpa
DOMAIN-SUFFIX,26.172.in-addr.arpa
DOMAIN-SUFFIX,27.172.in-addr.arpa
DOMAIN-SUFFIX,28.172.in-addr.arpa
DOMAIN-SUFFIX,29.172.in-addr.arpa
DOMAIN-SUFFIX,30.172.in-addr.arpa
DOMAIN-SUFFIX,31.172.in-addr.arpa
DOMAIN,console.gl-inet.com
DOMAIN-SUFFIX,168.192.in-addr.arpa
DOMAIN-SUFFIX,254.169.in-addr.arpa
DOMAIN-SUFFIX,huaweimobilewifi.com
DOMAIN,instant.arubanetworks.com
DOMAIN,setmeup.arubanetworks.com
################## EOF ##################