#########################################
# Sukka's Ruleset - Netease Music
# Last Updated: 2026-07-31T17:36:02.324Z
# Size: 5
# License: AGPL 3.0
# Homepage: https://ruleset.skk.moe
# GitHub: https://github.com/SukkaW/Surge
#
# This file contains rules for Netease Music.
#
# $content-hash-v1$:YAPQWcPkfWV5zKmbAN1LggBNSff7nh9TahlvEgsZ8fY$
#########################################
DOMAIN,7h15_ru1353t_1s_m4d3_by_5ukk4w.skk.moe
DOMAIN-SUFFIX,music.126.net
DOMAIN-SUFFIX,music.163.com
USER-AGENT,%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90
USER-AGENT,NeteaseMusic*
################## EOF ##################