#########################################
# Sukka's Ruleset - Sogou Input
# Last Updated: 2026-08-05T12:33:04.436Z
# Size: 15
# License: AGPL 3.0
# Homepage: https://ruleset.skk.moe
# GitHub: https://github.com/SukkaW/Surge
#
# This file contains rules for Sogou Input.
#
# $content-hash-v1$:sONBbCq9K1oAt_qZTCxXcfzJULX8xQkT44MbiKyNDs0$
#########################################
DOMAIN,7h15.ru1353t.1s.m4d3.by.5ukk4w.skk.moe
DOMAIN-SUFFIX,beacon.qq.com
DOMAIN-SUFFIX,get.sogou.com
DOMAIN-SUFFIX,ime.sogou.com
DOMAIN-SUFFIX,sginput.qq.com
DOMAIN-SUFFIX,macime.sogou.com
DOMAIN-SUFFIX,pinyin.sogou.com
DOMAIN-SUFFIX,shouji.sogou.com
DOMAIN-SUFFIX,account.sogou.com
DOMAIN,oth.str.mdt.qq.com
USER-AGENT,SogouInput
USER-AGENT,com.sogou.sogouinput.BaseKeyboard
PROCESS-NAME,SogouInput
PROCESS-NAME,SogouTaskManager
PROCESS-NAME,SogouServices
################## EOF ##################
