#########################################
# Sukka's Ruleset - Stream Services: Japan
# Last Updated: 2026-06-30T21:42:09.495Z
# Size: 28
# License: AGPL 3.0
# Homepage: https://ruleset.skk.moe
# GitHub: https://github.com/SukkaW/Surge
#
# - DMM
# - AbemaTV
# - niconico
# - Hulu Japan
# - encoreTVB JP
# - NHK Plus
#########################################
DOMAIN,7h1s_rul35et_i5_mad3_by_5ukk4w-ruleset.skk.moe
DOMAIN-SUFFIX,dmm.com
DOMAIN-SUFFIX,hulu.jp
DOMAIN-SUFFIX,tver.jp
DOMAIN-SUFFIX,abema.io
DOMAIN-SUFFIX,abema.tv
DOMAIN-SUFFIX,ameba.jp
DOMAIN-SUFFIX,dmc.nico
DOMAIN-SUFFIX,ameblo.jp
DOMAIN-SUFFIX,dmm.co.jp
DOMAIN-SUFFIX,socdm.com
DOMAIN-SUFFIX,happyon.jp
DOMAIN-SUFFIX,amebame.com
DOMAIN-SUFFIX,hayabusa.io
DOMAIN-SUFFIX,abema-tv.com
DOMAIN-SUFFIX,hayabusa.dev
DOMAIN-SUFFIX,nicovideo.jp
DOMAIN-SUFFIX,winticket.jp
DOMAIN-SUFFIX,amebaownd.com
DOMAIN-SUFFIX,hjholdings.jp
DOMAIN-SUFFIX,hayabusa.media
DOMAIN-SUFFIX,amebaowndme.com
DOMAIN-SUFFIX,dmm-extension.com
DOMAIN-SUFFIX,dokusho-ojikan.jp
DOMAIN-SUFFIX,location-plus.nhk.jp
DOMAIN,ds-linear-abematv.akamaized.net
USER-AGENT,AbemaTV*
USER-AGENT,Niconico*
################## EOF ##################