#########################################
# Sukka's Ruleset - Local DNS Mapping (BILIBILI)
# Last Updated: 2026-08-05T12:33:04.540Z
# Size: 19
# License: AGPL 3.0
# Homepage: https://ruleset.skk.moe
# GitHub: https://github.com/SukkaW/Surge
#
# This is an internal rule that is only referenced by sukka_local_dns_mapping.sgmodule
# Do not use this file in your Rule section, all entries are included in non_ip/domestic.conf already.
#
# $content-hash-v1$:iIrEFyvhkmzRKVsXQrcldz1yNuOezYRe0E72gfHKq5U$
#########################################
DOMAIN,7h15.ru1353t.1s.m4d3.by.5ukk4w.skk.moe
DOMAIN,acg.tv
DOMAIN,b23.tv
DOMAIN-SUFFIX,hdslb.com
DOMAIN-SUFFIX,biliapi.com
DOMAIN-SUFFIX,biliapi.net
DOMAIN-SUFFIX,bilibili.cn
DOMAIN-SUFFIX,biliimg.com
DOMAIN-SUFFIX,acgvideo.com
DOMAIN-SUFFIX,bilibili.com
DOMAIN-SUFFIX,bilicdn1.com
DOMAIN-SUFFIX,biligame.com
DOMAIN-SUFFIX,biligame.net
DOMAIN-SUFFIX,bilivideo.cn
DOMAIN-SUFFIX,bulicdn2.com
DOMAIN-SUFFIX,bilicomic.com
DOMAIN-SUFFIX,bilivideo.com
DOMAIN-SUFFIX,bilivideo.net
DOMAIN-SUFFIX,bilicomics.com
################## EOF ##################
