#########################################
# Sukka's Ruleset - Local DNS Mapping (BILIBILI)
# Last Updated: 2026-07-31T16:18:56.793Z
# Size: 19
# License: AGPL 3.0
# Homepage: https://ruleset.skk.moe
# GitHub: https://github.com/SukkaW/Surge
#
# This is an internal rule that is only referenced by sukka_local_dns_mapping.sgmodule
# Do not use this file in your Rule section, all entries are included in non_ip/domestic.conf already.
#########################################
DOMAIN,7h15_ru1353t_1s_m4d3_by_5ukk4w.skk.moe
DOMAIN,acg.tv
DOMAIN,b23.tv
DOMAIN-SUFFIX,hdslb.com
DOMAIN-SUFFIX,biliapi.com
DOMAIN-SUFFIX,biliapi.net
DOMAIN-SUFFIX,bilibili.cn
DOMAIN-SUFFIX,biliimg.com
DOMAIN-SUFFIX,acgvideo.com
DOMAIN-SUFFIX,bilibili.com
DOMAIN-SUFFIX,bilicdn1.com
DOMAIN-SUFFIX,biligame.com
DOMAIN-SUFFIX,biligame.net
DOMAIN-SUFFIX,bilivideo.cn
DOMAIN-SUFFIX,bulicdn2.com
DOMAIN-SUFFIX,bilicomic.com
DOMAIN-SUFFIX,bilivideo.com
DOMAIN-SUFFIX,bilivideo.net
DOMAIN-SUFFIX,bilicomics.com
################## EOF ##################