#########################################
# Sukka's Ruleset - Local DNS Mapping (BYTEDANCE)
# Last Updated: 2026-06-30T21:42:09.922Z
# Size: 70
# License: AGPL 3.0
# Homepage: https://ruleset.skk.moe
# GitHub: https://github.com/SukkaW/Surge
#
# This is an internal rule that is only referenced by sukka_local_dns_mapping.sgmodule
# Do not use this file in your Rule section, all entries are included in non_ip/domestic.conf already.
#########################################
DOMAIN,7h1s_rul35et_i5_mad3_by_5ukk4w-ruleset.skk.moe
DOMAIN-SUFFIX,coze.cn
DOMAIN-SUFFIX,okr.com
DOMAIN-SUFFIX,zjurl.cn
DOMAIN-SUFFIX,baike.com
DOMAIN-SUFFIX,bdurl.net
DOMAIN-SUFFIX,feishu.cn
DOMAIN-SUFFIX,pipix.com
DOMAIN-SUFFIX,zjcdn.com
DOMAIN-SUFFIX,bytecdn.cn
DOMAIN-SUFFIX,doubao.com
DOMAIN-SUFFIX,douyin.com
DOMAIN-SUFFIX,feishu.net
DOMAIN-SUFFIX,ixigua.com
DOMAIN-SUFFIX,ppximg.com
DOMAIN-SUFFIX,ppxvod.com
DOMAIN-SUFFIX,pstatp.com
DOMAIN-SUFFIX,rsproxy.cn
DOMAIN-SUFFIX,snssdk.com
DOMAIN-SUFFIX,volces.com
DOMAIN-SUFFIX,wukong.com
DOMAIN-SUFFIX,byteimg.com
DOMAIN-SUFFIX,bytescm.com
DOMAIN-SUFFIX,bytetcc.com
DOMAIN-SUFFIX,bytetos.com
DOMAIN-SUFFIX,dcarapi.com
DOMAIN-SUFFIX,dcarimg.com
DOMAIN-SUFFIX,dcarvod.com
DOMAIN-SUFFIX,feelgood.cn
DOMAIN-SUFFIX,feiliao.com
DOMAIN-SUFFIX,huoshan.com
DOMAIN-SUFFIX,toutiao.com
DOMAIN-SUFFIX,volccdn.com
DOMAIN-SUFFIX,dcarlive.com
DOMAIN-SUFFIX,ixgvideo.com
DOMAIN-SUFFIX,zijieapi.com
DOMAIN-SUFFIX,bytecdntp.com
DOMAIN-SUFFIX,bytedance.com
DOMAIN-SUFFIX,bytegoofy.com
DOMAIN-SUFFIX,dongchedi.com
DOMAIN-SUFFIX,douyincdn.com
DOMAIN-SUFFIX,douyinpay.com
DOMAIN-SUFFIX,douyinpic.com
DOMAIN-SUFFIX,douyinvod.com
DOMAIN-SUFFIX,feishucdn.com
DOMAIN-SUFFIX,feishupkg.com
DOMAIN-SUFFIX,ibytedapm.com
DOMAIN-SUFFIX,iesdouyin.com
DOMAIN-SUFFIX,ppxstatic.com
DOMAIN-SUFFIX,toutiaoimg.cn
DOMAIN-SUFFIX,volcvideo.com
DOMAIN-SUFFIX,bytednsdoc.com
DOMAIN-SUFFIX,dcarstatic.com
DOMAIN-SUFFIX,edge-byted.com
DOMAIN-SUFFIX,toutiaoimg.com
DOMAIN-SUFFIX,toutiaovod.com
DOMAIN-SUFFIX,volcengine.com
DOMAIN-SUFFIX,xiaoxiaapi.com
DOMAIN-SUFFIX,byteacctimg.com
DOMAIN-SUFFIX,ixiguavideo.com
DOMAIN-SUFFIX,oceanengine.com
DOMAIN-SUFFIX,toutiaopage.com
DOMAIN-SUFFIX,byted-static.com
DOMAIN-SUFFIX,douyinliving.com
DOMAIN-SUFFIX,douyinstatic.com
DOMAIN-SUFFIX,huoshanzhibo.com
DOMAIN-SUFFIX,toutiaocloud.com
DOMAIN-SUFFIX,byteeffecttos.com
DOMAIN-SUFFIX,huoshanstatic.com
DOMAIN-SUFFIX,toutiaostatic.com
################## EOF ##################