#########################################
# Sukka's Ruleset - Local DNS Mapping (XIAOMI)
# Last Updated: 2026-08-05T12:33:04.540Z
# Size: 19
# License: AGPL 3.0
# Homepage: https://ruleset.skk.moe
# GitHub: https://github.com/SukkaW/Surge
#
# This is an internal rule that is only referenced by sukka_local_dns_mapping.sgmodule
# Do not use this file in your Rule section, all entries are included in non_ip/domestic.conf already.
#
# $content-hash-v1$:VhJiUfkSH8sqixa97xj_DJoyTgXpKu0xZskUV1sWEyQ$
#########################################
DOMAIN,7h15.ru1353t.1s.m4d3.by.5ukk4w.skk.moe
DOMAIN-SUFFIX,mi.com
DOMAIN-SUFFIX,miui.com
DOMAIN-SUFFIX,mifile.cn
DOMAIN-SUFFIX,mipay.com
DOMAIN-SUFFIX,xiaomi.cn
DOMAIN-SUFFIX,duokan.com
DOMAIN-SUFFIX,mi-fds.com
DOMAIN-SUFFIX,mi-idc.com
DOMAIN-SUFFIX,mi-img.com
DOMAIN-SUFFIX,mijia.tech
DOMAIN-SUFFIX,miwifi.com
DOMAIN-SUFFIX,xiaomi.com
DOMAIN-SUFFIX,xiaomi.net
DOMAIN-SUFFIX,xiaomiev.com
DOMAIN-SUFFIX,gorouter.info
DOMAIN-SUFFIX,xiaoaisound.com
DOMAIN-SUFFIX,xiaomixiaoai.com
DOMAIN-SUFFIX,xiaomiyoupin.com
################## EOF ##################
