#########################################
# Sukka's Ruleset - LAN
# Last Updated: 2026-08-05T12:33:04.394Z
# Size: 12
# License: AGPL 3.0
# Homepage: https://ruleset.skk.moe
# GitHub: https://github.com/SukkaW/Surge
#
# Includes rules for LAN IP addresses and .local suffix.
#
# $content-hash-v1$:AcyY1IsPOA4BBFgKlSC14TLEln-zD7bAz8N-cXfvVlg$
#########################################
DOMAIN,7h15.ru1353t.1s.m4d3.by.5ukk4w.skk.moe
IP-CIDR,0.0.0.0/8
IP-CIDR,10.0.0.0/8
IP-CIDR,100.64.0.0/10
IP-CIDR,127.0.0.0/8
IP-CIDR,169.254.0.0/16
IP-CIDR,172.16.0.0/12
IP-CIDR,192.168.0.0/16
IP-CIDR,224.0.0.0/4
IP-CIDR6,::1/128
IP-CIDR6,fc00::/7
IP-CIDR6,fe80::/10
################## EOF ##################
