#########################################
# Sukka's Ruleset - Telegram ASN
# Last Updated: 2026-08-05T12:33:04.398Z
# Size: 6
# License: AGPL 3.0
# Homepage: https://ruleset.skk.moe
# GitHub: https://github.com/SukkaW/Surge
#
# This file contains ASN owned/used by Telegram Messenger.
# Note that unlike "ip/telegram" file which is based on officially released list by Telegram themselves. Use this file at your own risk.
#
# $content-hash-v1$:q-4xTNYSx86R21Js4bVczyxB2YPM0F8HmBEt-jbA44Y$
#########################################
DOMAIN,7h15.ru1353t.1s.m4d3.by.5ukk4w.skk.moe
IP-ASN,62041
IP-ASN,62014
IP-ASN,59930
IP-ASN,44907
IP-ASN,211157
################## EOF ##################
