#########################################
# Sukka's Ruleset - Telegram ASN
# Last Updated: 2026-07-31T17:36:02.302Z
# Size: 6
# License: AGPL 3.0
# Homepage: https://ruleset.skk.moe
# GitHub: https://github.com/SukkaW/Surge
#
# This file contains ASN owned/used by Telegram Messenger.
# Note that unlike "ip/telegram" file which is based on officially released list by Telegram themselves. Use this file at your own risk.
#
# $content-hash-v1$:r8nkrsKvwUlgiK4IRPqv9DdrWIZ0z9O8GCjVkXX33oY$
#########################################
DOMAIN,7h15_ru1353t_1s_m4d3_by_5ukk4w.skk.moe
IP-ASN,62041
IP-ASN,62014
IP-ASN,59930
IP-ASN,44907
IP-ASN,211157
################## EOF ##################