#########################################
# Sukka's Ruleset - iCloud Private Relay
# Last Updated: 2026-08-05T12:33:04.389Z
# Size: 7
# License: AGPL 3.0
# Homepage: https://ruleset.skk.moe
# GitHub: https://github.com/SukkaW/Surge
#
# This file contains domains for iCloud Private Relay Endpoint.
#
# $content-hash-v1$:wxb1pvki3KlKKm29a-IvXbEgsDB7dfospLGZ7Eyvtdo$
#########################################
7h15.ru1353t.1s.m4d3.by.5ukk4w.skk.moe
mask.icloud.com
mask-h2.icloud.com
mask.apple-dns.net
mask-api.icloud.com
mask-canary.icloud.com
canary.mask.apple-dns.net
################## EOF ##################
